version: '3.0' 
 
services:
  rasa:
    container_name: rasa
    # go to docker hub/rasa changelog to see what version and flavour of rasa that you want
    # Make sure that the version you specify is the same as the version that you pip installed
    image: rasa/rasa:2.1.2
    #Map port 5005 of local machine to 5005 of container
    ports:
      - 5005:5005
    # This command will copy everything in current directory to the /app directory in the container 
    volumes:
      - ./:/app
    command:
      - run

  app:
    image: action-server:latest 
    expose:
      - 5055